[package]
name = "tmc"
version = "1.0.4"
authors = ["HoolaBoola <jaime.heikkiladias@helsinki.fi>",
           "Robustic <juha.malinen@helsinki.fi>",
           "ShootingStar91 <arttu.kangas@helsinki.fi>",
           "Nooblue <joni.sikio@helsinki.fi>"]
edition = "2018"
description = "Command line interface for TMC, written in Rust."
license = "Apache-2.0"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.2.1"
clap = "2.3.3"
assert_cmd = "0.10"
predicates = "1"
anyhow = "1"
serde = "1"
serde_json = "1"
log = "0.4"
dirs = "3"
tmc-langs-util = { git = "https://github.com/rage/tmc-langs-rust/", rev = "13f3d55" }
tmc-langs-framework = { git = "https://github.com/rage/tmc-langs-rust/", rev = "13f3d55" }
tmc-langs = { git = "https://github.com/rage/tmc-langs-rust/", rev = "13f3d55" }
tmc-client = { git = "https://github.com/rage/tmc-langs-rust/", rev = "13f3d55" }
rpassword = "5.0.1"
mockall = "0.9.0"
indicatif = "0.15.0"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls", "multipart"] }
toml = "0.5"
isolang = "1"
crossterm = "0.19"
tui = { version = "0.14", default-features = false, features = ['crossterm'] }
termcolor = "1.1"
terminal_size = "0.1.16"

[build-dependencies]
clap = "2.3.3"
