[package]
name = "tmc"
version = "1.0.5"
authors = ["HoolaBoola <jaime.heikkiladias@helsinki.fi>",
           "Robustic <juha.malinen@helsinki.fi>",
           "ShootingStar91 <arttu.kangas@helsinki.fi>",
           "Nooblue <joni.sikio@helsinki.fi>"]
edition = "2021"
rust-version = "1.58.1"
description = "Command line interface for TMC, written in Rust."
license = "Apache-2.0"
build = "build.rs"

[dependencies]
anyhow = "1.0.56"
assert_cmd = "2.0.4"
crossterm = "0.23.0"
clap = "3.1.6"
clap_complete = "3.1.1"
dirs = "4.0.0"
indicatif = "0.16.2"
isolang = "2.1.0"
log = "0.4.14"
predicates = "2.1.1"
reqwest = { version = "0.11.9", default-features = false, features = ["blocking", "json", "rustls-tls", "multipart"] }
rpassword = "5.0.1"
serde = "1.0.136"
serde_json = "1.0.79"
termcolor = "1.1.3"
terminal_size = "0.1.17"
tmc-langs = { git = "https://github.com/rage/tmc-langs-rust/", rev = "8f41c8e535" }
toml = "0.5.8"
tui = { version = "0.17.0", default-features = false, features = ['crossterm'] }
url = "2.2.2"

[dev-dependencies]
mockall = "0.11.0"

[build-dependencies]
clap = "3.1.6"
clap_complete = "3.1.1"
