[package]
name = "tmc"
version = "1.1.1"
authors = ["HoolaBoola <jaime.heikkiladias@helsinki.fi>",
           "Robustic <juha.malinen@helsinki.fi>",
           "ShootingStar91 <arttu.kangas@helsinki.fi>",
           "Nooblue <joni.sikio@helsinki.fi>"]
edition = "2021"
rust-version = "1.58.1"
description = "Client for downloading, testing and submitting exercises through the TestMyCode system."
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.56"
clap = "3.1.6"
clap_complete = "3.1.1"
crossterm = "0.23.0"
indicatif = "0.16.2"
reqwest = { version = "0.11.9", default-features = false, features = ["blocking", "json", "rustls-tls", "multipart"] }
rpassword = "6.0.0"
serde = "1.0.136"
serde_json = "1.0.79"
termcolor = "1.1.3"
terminal_size = "0.1.17"
tmc-langs = { git = "https://github.com/rage/tmc-langs-rust/", tag = "0.24.0" }
toml = "0.5.8"
tui = { version = "0.17.0", default-features = false, features = ['crossterm'] }
url = "2.2.2"

[dev-dependencies]
assert_cmd = "2.0.4"
predicates = "2.1.1"

[build-dependencies]
clap = "3.1.6"
clap_complete = "3.1.1"
