[package]
name = "tmc-cli-rust"
version = "0.1.0"
authors = ["HoolaBoola <jaime.heikkiladias@helsinki.fi>",
           "Robustic <juha.malinen@helsinki.fi"]
edition = "2018"
description = "Command line interface for TMC, written in Rust."
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.3.3"
assert_cmd = "0.10"
predicates = "1"
