name: Linux

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install fmt and clippy
      run: |
        rustup component add rustfmt
        rustup component add clippy
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run fmt
      run: cargo fmt -- --check
    - name: Run clippy
      run: cargo clippy -- -D warnings