name: Linux

on: push

env:
  CARGO_TERM_COLOR: always

jobs:

  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install fmt and clippy
      run: |
        rustup component add rustfmt
        rustup component add clippy
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run fmt
      run: cargo fmt -- --check
    - name: Run clippy
      run: cargo clippy -- -D warnings

  release:
    needs: debug
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        target: [i686-unknown-linux-gnu, x86_64-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-multilib # required to build for 32-bit arch
      - name: Cargo build
        run: |
          rustup target add i686-unknown-linux-gnu
          cargo build -p tmc-cli-rust --release --verbose --target ${{ matrix.target }}
      - name: Deploy
        run: gsutil cp target/${{ matrix.target }}/release/tmc-cli-rust gs://${{ secrets.GCP_BUCKET }}/tmc-cli-rust/tmc-cli-rust-${{ matrix.target }}